---
- name: Create node-exporter container
  become: true
  docker_container:
    name: "{{ node_exporter_service_name }}"
    capabilities:
      - sys_time
    command: "{{ node_exporter_args }}"
    detach: true
    image: "{{ node_exporter_image }}"
    network_mode: host
    pid_mode: host
    ports:
      - "9100:9100"
    state: present
    volumes:
      - "/:/host:ro,rslave"
      # - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro"
  notify: restart node-exporter

- name: Create node-exporter service file
  become: true
  template:
    dest: "/etc/systemd/system/{{ node_exporter_service_name }}.service"
    src: "templates/node-exporter.service.j2"
    mode: 0664
  notify: restart node-exporter

- name: Enable node-exporter service
  become: true
  service:
    name: "{{ node_exporter_service_name }}.service"
    state: started
    enabled: yes
